# Generated by Django 2.2 on 2021-05-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validated_show_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='release_date',
            field=models.DateField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
