# Generated by Django 2.2 on 2021-05-29 09:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('validated_show_app', '0004_auto_20210529_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='release_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
